services:
  gujarat-store:
    container_name: the-gujarat-store
    image: the-gujarat-store
    build:
      context: .
      args:
        - MONGODB_URL=${MONGODB_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXT_PUBLIC_APP_BASE_URL=${NEXT_PUBLIC_APP_BASE_URL}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
        - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
        - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
        - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
        - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}
        - SHIPROCKET_EMAIL=${SHIPROCKET_EMAIL}
        - SHIPROCKET_PASSWORD=${SHIPROCKET_PASSWORD}
        - SHIPROCKET_API_BASE_URL=${SHIPROCKET_API_BASE_URL}
        - SHIPROCKET_DEFAULT_PICKUP_LOCATION=${SHIPROCKET_DEFAULT_PICKUP_LOCATION}
        - CRON_SECRET=${CRON_SECRET}
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_APP_BASE_URL=${NEXT_PUBLIC_APP_BASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}
      - SHIPROCKET_EMAIL=${SHIPROCKET_EMAIL}
      - SHIPROCKET_PASSWORD=${SHIPROCKET_PASSWORD}
      - SHIPROCKET_API_BASE_URL=${SHIPROCKET_API_BASE_URL}
      - SHIPROCKET_DEFAULT_PICKUP_LOCATION=${SHIPROCKET_DEFAULT_PICKUP_LOCATION}
      - CRON_SECRET=${CRON_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
